// <auto-generated />
using System;
using IFAVALIACAO.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IFAVALIACAO.API.Migrations
{
    [DbContext(typeof(IFDbContext))]
    [Migration("20200220032622_create_table_Vaca")]
    partial class create_table_Vaca
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IFAVALIACAO.API.Domain.Entites.Fazenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<bool>("Deletado");

                    b.Property<string>("Endereco");

                    b.Property<string>("Estado");

                    b.Property<string>("InscricaoEstadual");

                    b.Property<string>("NomeFazenda");

                    b.Property<string>("NomeProprietario");

                    b.HasKey("Id");

                    b.ToTable("Fazenda");
                });

            modelBuilder.Entity("IFAVALIACAO.API.Domain.Entites.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<bool>("Deletado");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("IFAVALIACAO.API.Domain.Entites.Vaca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime?>("DataNascimento");

                    b.Property<bool>("Deletado");

                    b.Property<Guid>("FazendaId");

                    b.Property<string>("GrauSanguinio");

                    b.Property<int?>("Ipp");

                    b.Property<string>("Nome");

                    b.Property<string>("NomePai");

                    b.Property<int>("Numero");

                    b.Property<int?>("NumeroPai");

                    b.Property<int?>("OrdemParto");

                    b.Property<string>("Raca");

                    b.Property<Guid?>("VacaMaeId");

                    b.HasKey("Id");

                    b.HasIndex("FazendaId");

                    b.HasIndex("VacaMaeId");

                    b.ToTable("Vaca");
                });

            modelBuilder.Entity("IFAVALIACAO.API.Domain.Entites.Vaca", b =>
                {
                    b.HasOne("IFAVALIACAO.API.Domain.Entites.Fazenda", "Fazenda")
                        .WithMany()
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IFAVALIACAO.API.Domain.Entites.Vaca", "VacaMae")
                        .WithMany("VacasMaes")
                        .HasForeignKey("VacaMaeId");
                });
#pragma warning restore 612, 618
        }
    }
}
